"""
Sovereign Gotham - Distillation Teacher Engine
Generates deep multi-hop cognitive reasoning traces (<thought>...</thought>)
from raw declassified documents (CIA, NSA, FBI) and the Gotham Knowledge Graph.
Supports both AGY CLI (Gemini 3.8 Flash High) and offline Ontological Synthesis.
"""

from __future__ import annotations

import json
import logging
import re
import subprocess
from typing import Any

from pydantic import BaseModel, Field

from ontology.graph import GothamKnowledgeGraph
from ontology.models import Operation, Target_Entity
from ontology.osdk_client import SovereignOSDKClient

logger = logging.getLogger("SovereignGotham.DistillTeacher")


class RawDistillSample(BaseModel):
    """Raw sample generated by the teacher before curation."""
    source_id: str
    directive: str
    context: dict[str, Any] = Field(default_factory=dict)
    teacher_thought: str
    teacher_output: dict[str, Any]
    metadata: dict[str, Any] = Field(default_factory=dict)


class DistillationTeacherEngine:
    """
    Teacher engine that synthesizes high-density reasoning traces.
    Combines graph multi-hop inference with contextual declassified records.
    """

    def __init__(
        self,
        graph: GothamKnowledgeGraph,
        agy_model: str = "gemini-3.8-flash-high",
        timeout: float = 90.0,
    ):
        self.graph = graph
        self.osdk = SovereignOSDKClient(graph)
        self.agy_model = agy_model
        self.timeout = timeout

    def synthesize_with_agy_cli(
        self,
        doc_record: dict[str, Any],
        target: Target_Entity | None = None,
        operation: Operation | None = None,
    ) -> RawDistillSample:
        """
        Calls AGY CLI (Gemini 3.8 Flash High) to perform high-grade intelligence
        reasoning and extraction over a declassified document record.
        """
        doc_id = doc_record.get("doc_id", "DOC-UNKNOWN")
        title = doc_record.get("title", "UNTITLED DISPATCH")
        body_snippet = doc_record.get("body", "")[:1800]
        classification = doc_record.get("classification", "DECLASSIFIED")

        target_name = target.name if target else "COVERT_ACTOR"
        target_threat = target.threat_level if target else "HIGH"
        op_codename = operation.codename if operation else "PROJECT_ANALYSIS"

        directive = (
            f"Perform exhaustive intelligence assessment on record {doc_id} ('{title[:70]}'). "
            f"Cross-reference target entity '{target_name}' ({target_threat}) within operational campaign '{op_codename}' "
            f"and formulate deterministic containment protocol under CAPCO rules."
        )

        prompt = (
            f"You are the Senior Intelligence Analyst for Sovereign Gotham (Palantir Ontology Engine).\n"
            f"Analyze this declassified intelligence record:\n"
            f"Record ID: {doc_id}\n"
            f"Title: {title}\n"
            f"Content Excerpt:\n{body_snippet}\n\n"
            f"Associated Target: {target_name} ({target_threat})\n"
            f"Active Campaign: {op_codename}\n\n"
            f"You MUST output your response strictly in two sections:\n"
            f"[REASONING_CHAIN]\n"
            f"1. Ingestion: Provenance verification, document authenticity, and classification check.\n"
            f"2. Threat Vectors: Identify active risks, hostile tradecraft, and counter-espionage vulnerabilities.\n"
            f"3. Ontological Grounding: Link entities to the Gotham knowledge graph (Documents, Operations, Targets).\n"
            f"4. Strategic Decision: Formulate strict Rules of Engagement (ROE) and operational containment directives.\n"
            f"[/REASONING_CHAIN]\n\n"
            f"```json\n"
            f"{{\n"
            f'  "document_id": "{doc_id}",\n'
            f'  "threat_rating": "{target_threat}",\n'
            f'  "course_of_action": ["Step 1 directive", "Step 2 directive", "Step 3 directive"],\n'
            f'  "compliance_status": "PERMITTED",\n'
            f'  "confidence_score": 0.94\n'
            f"}}\n"
            f"```\n"
        )

        try:
            logger.info(f"[*] Calling AGY CLI ({self.agy_model}) for record {doc_id}...")
            proc = subprocess.run(
                ["agy", "--model", self.agy_model, "-p", prompt],
                capture_output=True,
                text=True,
                encoding="utf-8",
                errors="ignore",
                timeout=self.timeout,
            )

            if proc.returncode == 0 and proc.stdout:
                raw_out = proc.stdout.strip()
                thought_match = re.search(r"\[REASONING_CHAIN\](.*?)\[/REASONING_CHAIN\]", raw_out, re.DOTALL)
                json_match = re.search(r"```json(.*?)```", raw_out, re.DOTALL)

                if thought_match and json_match:
                    thought_text = thought_match.group(1).strip()
                    json_text = json_match.group(1).strip()
                    parsed_json = json.loads(json_text)

                    return RawDistillSample(
                        source_id=doc_id,
                        directive=directive,
                        context={
                            "document_id": doc_id,
                            "title": title,
                            "classification": classification,
                            "body_excerpt": body_snippet[:1000],
                            "target": {"name": target_name, "threat_level": target_threat},
                            "operation": {"codename": op_codename},
                        },
                        teacher_thought=thought_text,
                        teacher_output=parsed_json,
                        metadata={"generator": f"AGY-CLI-{self.agy_model}"},
                    )
        except Exception as e:
            logger.warning(f"AGY CLI call failed for {doc_id}: {e}. Falling back to ontological synthesis.")

        # Fallback to deterministic ontological synthesis if AGY CLI unavailable
        return self.synthesize_ontological_reasoning(doc_record, target, operation)

    def synthesize_ontological_reasoning(
        self,
        doc_record: dict[str, Any],
        target: Target_Entity | None = None,
        operation: Operation | None = None,
    ) -> RawDistillSample:
        """Deterministic fallback synthesizer."""
        doc_id = doc_record.get("doc_id", "DOC-UNKNOWN")
        title = doc_record.get("title", "UNTITLED DISPATCH")
        body_snippet = doc_record.get("body", "")[:1200]
        classification = doc_record.get("classification", "DECLASSIFIED")

        target_name = target.name if target else "COVERT_ACTOR"
        target_threat = target.threat_level if target else "HIGH"
        op_codename = operation.codename if operation else "PROJECT_ANALYSIS"

        directive = (
            f"Perform exhaustive intelligence assessment on record {doc_id} ('{title[:70]}'). "
            f"Cross-reference target entity '{target_name}' ({target_threat}) within operational campaign '{op_codename}' "
            f"and formulate deterministic containment protocol under CAPCO rules."
        )

        context = {
            "document_id": doc_id,
            "title": title,
            "classification": classification,
            "body_excerpt": body_snippet,
            "target": {"name": target_name, "threat_level": target_threat},
            "operation": {"codename": op_codename},
        }

        thought = (
            f"1. Ingestion & Provenance Vetting:\n"
            f"   - Processing declassified record {doc_id} ({classification}).\n"
            f"   - Assessing institutional origin, metadata authenticity, and chronological boundaries.\n"
            f"2. Entity & Threat Vector Extraction:\n"
            f"   - Target identified: '{target_name}', active threat classification: {target_threat}.\n"
            f"   - Evaluating cross-agency touchpoints and potential clandestine courier links.\n"
            f"3. Ontological Graph Pivot:\n"
            f"   - Connecting record {doc_id} to operational mandate '{op_codename}'.\n"
            f"   - Checking for conflicting procedures and active compartmentalization safeguards.\n"
            f"4. Counter-Intelligence Risk Assessment:\n"
            f"   - Screening for disinformation vectors, operational friction, and source vulnerabilities.\n"
            f"   - Applying M.I.C.E. matrix to identify potential target leverage points.\n"
            f"5. Operational Synthesis & Directive Formulation:\n"
            f"   - Formulating three-phase containment procedure: Passive SIGINT surveillance, courier mapping, and secure isolation.\n"
            f"   - Verifying compliance with national command authority and ROE guidelines."
        )

        output = {
            "document_id": doc_id,
            "program_codename": op_codename,
            "target_evaluated": target_name,
            "threat_rating": target_threat,
            "classification_level": classification,
            "analytical_assessment": {
                "provenance": "VALIDATED_HISTORICAL_RECORD",
                "counter_intelligence_risk": "MODERATE_TO_HIGH",
                "primary_vulnerability": "COMMUNICATIONS_INTERCEPTION",
            },
            "course_of_action": [
                {"phase": 1, "action": "Establish passive SIGINT monitoring around target perimeter", "status": "IMMEDIATE"},
                {"phase": 2, "action": "Cross-reference target courier links with Gotham Graph nodes", "status": "PENDING_VERIFICATION"},
                {"phase": 3, "action": "Execute controlled containment upon isolation in neutral sector", "status": "CONTINGENT_ON_PID"},
            ],
            "compliance_status": "VALIDATED_ROE",
            "confidence_score": 0.95,
        }

        return RawDistillSample(
            source_id=doc_id,
            directive=directive,
            context=context,
            teacher_thought=thought,
            teacher_output=output,
            metadata={"generator": "DistillationTeacherEngine-Heuristic"},
        )
